version: '3.6'
services:
  python:
    build: .
    volumes:
      - ./:/home
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu ]
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    command: /bin/bash
